# Generated by Django 5.2.3 on 2025-07-02 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('yoga', 'Yoga'), ('zumba', 'Zumba'), ('hiit', 'HIIT'), ('pilates', 'Pilates'), ('cardio', 'Cardio'), ('strength', 'Strength Training')], help_text='Type of fitness class', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the class')),
                ('instructor', models.CharField(help_text='Name of the instructor', max_length=100)),
                ('datetime', models.DateTimeField(help_text='Date and time of the class (stored in UTC)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of the class in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('total_slots', models.PositiveIntegerField(help_text='Total number of available slots', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_slots', models.PositiveIntegerField(help_text='Number of currently available slots', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitness Class',
                'verbose_name_plural': 'Fitness Classes',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client making the booking', max_length=100)),
                ('client_email', models.EmailField(help_text='Email address of the client', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('booking_time', models.DateTimeField(auto_now_add=True, help_text='When the booking was made')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the booking is still active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the booking')),
                ('fitness_class', models.ForeignKey(help_text='The fitness class being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.fitnessclass')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_time'],
                'unique_together': {('fitness_class', 'client_email')},
            },
        ),
    ]
